apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-service
  name: {{ .Release.Name }}-service 
spec:
  ports:
  - nodePort: 30250
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-deployment
  sessionAffinity: None
  type: NodePort
